sudo: false
language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --ignore-engines
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - if [[ -n "${NPM_TOKEN}" ]]; then echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc; fi
        - yarn run semantic-release
