sudo: false
language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --ignore-engines

jobs:
  include:
    - stage: test
      script:
        - yarn run test
    - stage: release
      node_js: lts/*
      before_install:
        - yarn global add greenkeeper-lockfile@1
      before_script:
        - greenkeeper-lockfile-update
      script:
        - if [[ -n "${NPM_TOKEN}" ]]; then echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc; fi
        - yarn run semantic-release
      after_script:
        - greenkeeper-lockfile-upload
